ProductDeliveryManagement/ProductDeliveryManagement/Controllers/DeliveryPeopleController.cs
using ProductDeliveryManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;

namespace ProductDeliveryManagement.Controllers
{
    public class DeliveryPeopleController : Controller
    {
        DeliveryManagementDbContext db = new DeliveryManagementDbContext();
        // GET: DeliveryPeople
        public ActionResult Index(int page=1)
        {
            return View(db.DeliveryPeople.OrderBy(x => x.DeliveryPersonId).ToPagedList(page, 5));
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(DeliveryPerson person)
        {
            if(ModelState.IsValid)
            {
                db.DeliveryPeople.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }
    }
}

ProductDeliveryManagement/ProductDeliveryManagement/Controllers/OrderDeliveriesController.cs
using ProductDeliveryManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;
namespace ProductDeliveryManagement.Controllers
{
    public class OrderDeliveriesController : Controller
    {
        DeliveryManagementDbContext db = new DeliveryManagementDbContext();
        // GET: OrderDeliveries
        public ActionResult Index(int page = 1)
        {
            var data = db.OrdersDeliveries
                .OrderBy(x=> x.OrderDeliveryId)
                .ToPagedList(page, 5);
            return View(data);
        }
        public ActionResult Edit(int id)
        {
            return View(db.OrdersDeliveries.FirstOrDefault(x=> x.OrderDeliveryId == id));
        }
        [HttpPost]
        public ActionResult Edit(OrderDelivery delivery)
        {
            if (ModelState.IsValid)
            {
                delivery.IsDelivered = true;
                db.Entry(delivery).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(delivery);
        }
    }
}

ProductDeliveryManagement/ProductDeliveryManagement/Controllers/ProductsController.cs
using ProductDeliveryManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;
using X.PagedList.Mvc;


namespace ProductDeliveryManagement.Controllers
{
    public class ProductsController : Controller
    {
        DeliveryManagementDbContext db = new DeliveryManagementDbContext();
        // GET: Products
        public ActionResult Index(int page=1)
        {
            return View(db.Products.OrderBy(x=>x.ProductId).ToPagedList(page, 5));
        }
        public ActionResult Create() 
        { 
            return View();
        }
        [HttpPost]
        public ActionResult Create(Product product)
        {
            if(ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }
    }
}

ProductDeliveryManagement/ProductDeliveryManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DMS</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;1,100;1,200;1,300&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    @RenderSection("styles", false)
    <style>
        body {
            padding-top: 70px;
            font-family: 'Fira Sans', sans-serif;
            font-family: 'Roboto', sans-serif;
        }

        .main {
            min-height: calc(100vh - 130px);
        }
    </style>
</head>
<body>
    <div class="navbar bg-light fixed-top navbar-expand-md shadow-sm">
        <div class="container">

            <span class="navbar-brand">DMS <sup>Demo</sup>Application</span>


            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ms-auto">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Product items", "Index", "Products", new { }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Orders", "Index", "Orders", new { }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Delivery people", "Index", "DeliveryPeople", new { }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Order Deliverires", "Index", "OrderDeliveries", new { }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container main">
        @RenderBody()


    </div>
    <footer class="container">
        <p>&copy; @DateTime.Now.Year - DMS</p>
    </footer>
    @RenderSection("scripts", false)
</body>
</html>